export const regions = [
  { value: 'arusha', label: 'Arusha' },
  { value: 'dar-es-salaam', label: 'Dar es Salaam' },
  { value: 'dodoma', label: 'Dodoma' },
  { value: 'geita', label: 'Geita' },
  { value: 'iringa', label: 'Iringa' },
  { value: 'kagera', label: 'Kagera' },
  { value: 'katavi', label: 'Katavi' },
  { value: 'kigoma', label: 'Kigoma' },
  { value: 'kilimanjaro', label: 'Kilimanjaro' },
  { value: 'lindi', label: 'Lindi' },
  { value: 'manyara', label: 'Manyara' },
  { value: 'mara', label: 'Mara' },
  { value: 'mbeya', label: 'Mbeya' },
  { value: 'morogoro', label: 'Morogoro' },
  { value: 'mtwara', label: 'Mtwara' },
  { value: 'mwanza', label: 'Mwanza' },
  { value: 'pwani', label: 'Pwani' },
  { value: 'rukwa', label: 'Rukwa' },
  { value: 'ruvuma', label: 'Ruvuma' },
  { value: 'shinyanga', label: 'Shinyanga' },
  { value: 'simiyu', label: 'Simiyu' },
  { value: 'singida', label: 'Singida' },
  { value: 'tabora', label: 'Tabora' },
  { value: 'tanga', label: 'Tanga' },
  { value: 'katavi', label: 'Katavi' },
  { value: 'songwe', label: 'Songwe' },

];
